#!/bin/bash

if [[ $EUID -ne 0 ]];
then
  exec sudo /bin/bash "$0" "$@"
fi

while [[ $# -gt 0 ]]; do
  case $1 in
    -c|--container)
      container=$2
      shift # past argument
      shift # past value
      ;;
    -u|--user)
      user="$2"
      shift # past argument
      shift # past value
      ;;
    -s|--shell)
      shell="$2"
      shift # past argument
      shift # past value
      ;;
    *)
      shift # past argument
      ;;
  esac
done

container=${container:-UNSPECIFIED}
user=${user:-root}
shell=${shell:-/bin/bash}

container_dir=/var/lib/machines
container_loc="${container_dir}/${container}"

echo -e "container is ... $container"
echo -e "  Can be specified with \`-c|--container <container>\`"
echo -e "  Available containers: `ls -C ${container_dir}`"

if [[ "${container}" == UNSPECIFIED || ! -d "${container_loc}" ]] ; then
  echo -e "  A valid container must be specified but is not. Exit."
  exit 1
fi

echo -e "user is ........ $user"
echo -e "  Can be specified with \`-u|--user <user>\`"
echo -e "  Available users: `awk -F ':' '\$3>=1000 || \$3==0 {print \$1}' /etc/passwd | tr '\n' ' '`"

echo -e "shell is ....... $shell"
echo -e "  Can be  with \`-s|--shell <shell>\`)"
echo -e "  Available shells: `cat "${container_loc}/etc/shells" | sed '/^#/d'| tr '\n' ' '`"

read -r -p "Are you sure? [y/N] " response
case "$response" in
  [yY][eE][sS]|[yY]) 
    systemd-nspawn \
      -D "${container_loc}" \
      --resolv-conf=replace-stub \
      --as-pid2 \
      --bind=/var/cache/pacman/pkg \
      -u "${user}" \
      "$shell"
    ;;
  *)
    echo -e "Exit"
    ;;
esac
